package rediffmailPac;
// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.edge.EdgeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class RediffmailSuiteTest {
	
	
  private WebDriver driver;
  
  
  @Before
  public void setUp() {
	System.out.println("***********Bafore annotation method running*************");
	//Creating the environment variable to make the system under stand the path of chromedriver executable 
	//String path = System.getProperty("user.dir");
	//System.setProperty("webdriver.chrome.driver", path+"\\chromedriver.exe") ;
	
	//Control the browser - finding elements on the application opened in browser and performing action like click, type, etc.
    //driver = new ChromeDriver();
	
	//Creating the environment variable to make the system under stand the path of geckodriver executable 
	//String path = System.getProperty("user.dir");
	//System.setProperty("webdriver.gecko.driver", path+"\\geckodriver.exe") ;
	
	//Control the browser - finding elements on the application opened in browser and performing action like click, type, etc.
    //driver = new FirefoxDriver();
	
	//Creating the environment variable to make the system under stand the path of edgedriver executable 
	String path = System.getProperty("user.dir");
	System.setProperty("webdriver.edge.driver", path+"\\msedgedriver.exe") ;
	
	//Control the browser - finding elements on the application opened in browser and performing action like click, type, etc.
    driver = new EdgeDriver();
	
	
    
  }
  
  
  @After
  public void tearDown() {
	System.out.println("************After Annotation method running*****************");
	
	//Will kill the class instance (Chromedriver/FirefoxDriver/Edgedriver class) and close all browser window
    driver.quit();
  }
  
  
  @Test
  public void rediffmailLogin() {
	System.out.println("**************Test Case running*************");
	  
    // Test name: RediffmailLogin
    // Step # | name | target | value
	  
    // 1 | open | /cgi-bin/login.cgi | 
	//Get () method is used to navigate to URL
    driver.get("https://mail.rediff.com/cgi-bin/login.cgi");
    
    // 2 | setWindowSize | 1382x744 | 
    //Setting the size of the window
    driver.manage().window().setSize(new Dimension(1382, 744));
    
    // 3 | click | id=login1 | 
    //Click on the username edit box
    driver.findElement(By.id("login1")).click();
    
    
    // 4 | type | id=login1 | selenium.testmay2017
    //Type on the username edit box
    driver.findElement(By.id("login1")).sendKeys("selenium.testmay2017");
    
    
    // 5 | click | id=password | 
    //Click on password edit box
    driver.findElement(By.id("password")).click();
    
    
    // 6 | type | id=password | test@1234
    //Type on Password edit box
    driver.findElement(By.id("password")).sendKeys("test@1234");
    
    
    // 7 | click | name=proceed | 
    //Click on Sign in button
    driver.findElement(By.name("proceed")).click();
    
    
    // 8 | click | linkText=Logout | 
    //Click on Logout link
    driver.findElement(By.linkText("Logout")).click();
    
    
    // 9 | close |  | 
    //Close the current browser window
    driver.close();
  }
}
